### ISSUE TITLE
poetry.lock is out of sync with pyproject.toml

### ISSUE THREAD

**Issue by arr-ee** [airbytehq/airbyte-python-cdk#125]
Fresh checkout of the repo fails during dependencies installation: 

```
❯ git show HEAD --quiet
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
commit 3e671b877dca7fd47d125fd4af1124c65c3c8416 (HEAD -> main, upstream/main, upstream/HEAD)
Author: Aaron ("AJ") Steers <aj@airbyte.io>
Date:   Wed Dec 4 16:42:08 2024 -0800

    ci: dont create builder pr if sdm publish fails (#124)
❯ poetry install --all-extras
Installing dependencies from lock file

pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
```

#105 appears to be the culprit, which sort of makes sense given its scope. 

Curiously, CI did not catch this since lock file de-sync only [became an error in 1.8.0](https://github.com/python-poetry/poetry/pull/8737), and CI is running 1.7.1, so it moves along on cached dependencies: https://github.com/airbytehq/airbyte-python-cdk/actions/runs/12170943912/job/33946917673#step:5:13

I will open a PR to re-sync `poetry.lock` (luckily it's just a bunch of packages that are no longer dependencies); let me know if you'd like me to also bump poetry requirements for CI and devenv, or introduce some other way of catching this in the future.

**Comment by natikgadzhi** [comment]
Worth figuring out if we can bump poetry in CI to 1.8+ then. Poetry.lock mismatch no bueno.

**Comment by aaronsteers** [comment]
@arr-ee - Thanks for logging this, and for the PR. The lock file may have ended up as a merge of a few branches, and if not re-locked, it might cause the symptom we're seeing. I'll go ahead and merge #126 and then look at the other.

**Comment by aaronsteers** [comment]
@arr-ee - Above is merged - as follow-on, I added an explicit `poetry check` step here in this PR:

- https://github.com/airbytehq/airbyte-python-cdk/pull/140

With that, plus your changes in #128, we should be good to close this.

**Comment by aaronsteers** [comment]
I think that wraps it up - thanks again for the contributions, @arr-ee! 

cc @natikgadzhi (fyi, this is now closed+resolved)
